### ISSUE TITLE
siteshooter --init issue in docker

### ISSUE THREAD

**Issue by ykomarov** [devopsgroup-io/siteshooter#98]
```
root@56b6f410607b:~# siteshooter --init
/usr/local/lib/node_modules/siteshooter/lib/cli.js:95
        var flattenAliases = Object.entries(aliases).join().split(','),
                                    ^

TypeError: Object.entries is not a function
    at Object.parse (/usr/local/lib/node_modules/siteshooter/lib/cli.js:95:37)
    at Object.fromCli [as cli] (/usr/local/lib/node_modules/siteshooter/lib/siteshooter.js:102:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/siteshooter/bin/siteshooter.js:35:20)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
```

Docker image: **node:6**, clean install

I have tried to install via npm and from sources - result doesn't change

**Comment by stevebritton** [comment]
@ykomarov, 

I just updated the code and tested in Node:6, so you're good to go now. Let me know if you experience any issues.

-Steve
